//! Raw FFI bindings, generated by bindgen at build time.
//!
//! `ort`  — the ONNX Runtime plugin-EP C ABI (OrtApi/OrtEpApi/OrtEpFactory/OrtEp/…).
//! `mlx`  — the mlx-c C API, bound DIRECTLY (no mlx-rs crate).

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]
pub mod ort {
    include!(concat!(env!("OUT_DIR"), "/ort.rs"));
}

#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clippy::all
)]
pub mod mlx {
    include!(concat!(env!("OUT_DIR"), "/mlx.rs"));
}
